# @package hydra.sweeper

_target_: hydra._internal.sweeper.optuna.OptunaSweeper
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 123
direction: minimize
study_name: optuna_sweep
storage: null
n_trials: 20
n_jobs: 1
max_failure_rate: 0.0

params:
  # Data Parameters
  data.sequence_length: range(6, 24, 6)  # [6, 12, 18]
  data.batch_size: choice(8, 16)  # [8, 16]

  # Model Parameters (CNNLSTM)
  model.lstm_hidden_dim: choice(64, 128, 256)
  model.n_lstm_layers: choice(1, 2)
  model.lstm_dropout: interval(0.1, 0.5)
  
  # CNN Backbone Parameters
  model.cnn_init_dim: choice(32, 64)
  model.cnn_depth: choice(2, 3)
  model.cnn_dropout_rate: interval(0.1, 0.5)

  # Training Parameters
  training.lr: interval(1e-4, 1e-3) 