# @package hydra.sweeper

_target_: hydra.sweeper.optuna._OptunaSweeper
sampler:
  _target_: optuna.samplers.TPESampler
  seed: 123
direction: minimize
storage: sqlite:///optuna_studies.db
study_name: climate_model_optimization
n_trials: 20
n_jobs: 1

# Parameter notation for command line will be different
# These settings are just the defaults if not overridden by command line
params:
  data.sequence_length: choice(6, 12, 18, 24)
  data.batch_size: choice(8, 16, 32)
  model.lstm_hidden_dim: choice(64, 128, 256, 512)
  model.n_lstm_layers: choice(1, 2, 3)
  model.lstm_dropout: choice(0.1, 0.2, 0.3, 0.5)
  model.cnn_init_dim: choice(32, 64, 128)
  model.cnn_depth: choice(2, 3, 4)
  model.cnn_dropout_rate: choice(0.1, 0.2, 0.3, 0.5)
  training.lr: choice(5e-5, 1e-4, 5e-4, 1e-3, 5e-3) 