# @package _global_

defaults:
  - data: default
  - model: cnnlstm
  - training: default
  - trainer: default
  # The sweeper will be explicitly provided via command line with -m
  - _self_

# Global configs
seed: 42

# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "cse-151b-competition"
wandb_entity: "saem-uc-san-diego"
run_name: "enhanced_CNNLSTM_s${data.sequence_length}_b${data.batch_size}_L${model.lstm_hidden_dim}x${model.n_lstm_layers}dp${model.lstm_dropout}_bidir${model.bidirectional}_C${model.cnn_init_dim}x${model.cnn_depth}k${model.cnn_kernel_size}dp${model.cnn_dropout_rate}_act${model.cnn_activation_type}_attn${model.use_attention}h${model.attention_heads}_lr${training.lr}_wd${training.weight_decay}_opt${training.optimizer}_gradclip${training.gradient_clip_val}_lblsmooth${training.label_smoothing}_schP${training.lr_scheduler_patience}F${training.lr_scheduler_factor}minLR${training.lr_scheduler_min_lr}_cbP${trainer.callbacks.2.patience}delta${trainer.callbacks.2.min_delta}_prec${trainer.precision}_gradacc${trainer.accumulate_grad_batches}_pool${model.adaptive_pool_size}_projfact${model.feature_projection_factor}"
wandb_group: "Enhanced_Hyperparameter_Sweep"

# Optuna metric to optimize
optimized_metric: val/loss

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}
    subdir: ${hydra.job.num}
