# @package _global_

defaults:
  - data: default
  - model: cnnlstm
  - training: default
  - trainer: default
  - override hydra/sweeper: optuna
  - _self_

# Global configs
seed: 42

# Wandb logging, all arguments are only used if use_wandb is set to true
use_wandb: true
wandb_project: "cse-151b-competition"
wandb_entity: "saem-uc-san-diego"
run_name: "Optuna_CNNLSTM_Sweep"

# Optuna metric to optimize - Hydra will pass this to the sweeper
optimized_metric: val/loss

# Path to a checkpoint to load. If set, will load this checkpoint and resume training (evaluation)
ckpt_path: null

hydra:
  job:
    chdir: true
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}_${hydra.job.name}
    subdir: ${hydra.job.num}
  sweeper:
    study_name: cnnlstm_optuna_study
    storage: null  # Use in-memory storage
    direction: minimize
    n_trials: 20  # Number of trials to run
    n_jobs: 1     # Run 1 trial at a time (change to run multiple trials in parallel)
